<?php
/**
 * codes_ready.php — Displays newly purchased registration codes.
 *
 * Reached via redirect from kashier/callback.php after a successful
 * codes-{uid}-{count}-{ts} payment.
 *
 * Codes were generated (or will have been generated by webhook) with
 * notes = "kashier-order:{order_id}" so we can retrieve them by order.
 */

require_once(__DIR__ . '/../../config.php');

require_login();

$syscontext = context_system::instance();
require_capability('local/registrationcodes:generate', $syscontext);

$order_id = required_param('order_id', PARAM_ALPHANUMEXT);

// ── Security: order_id must belong to the logged-in user ──────────────────────
// Format: codes-{uid}-{count}-{ts}
$parts    = explode('-', $order_id);
$pay_uid  = isset($parts[1]) ? (int) $parts[1] : 0;

if (!$pay_uid || $pay_uid !== (int) $USER->id) {
    redirect(new moodle_url('/'), 'Unauthorized.', null, \core\output\notification::NOTIFY_ERROR);
}

// ── Fetch codes generated for this order ──────────────────────────────────────
$notes_tag = 'kashier-order:' . $order_id;
$codes     = $DB->get_records(
    'local_regcodes',
    ['notes' => $notes_tag, 'created_by' => $USER->id],
    'timecreated ASC',
    'id, code, status'
);

$PAGE->set_url(new moodle_url('/local/registrationcodes/codes_ready.php', ['order_id' => $order_id]));
$PAGE->set_context($syscontext);
$PAGE->set_title(get_string('codesready_title', 'local_registrationcodes'));
$PAGE->set_heading(get_string('codesready_title', 'local_registrationcodes'));

echo $OUTPUT->header();
?>
<div class="container al-codesready-wrap" dir="rtl" style="max-width:680px;margin:40px auto;">
  <div class="card shadow-sm">
    <div class="card-body">
      <h2 class="card-title mb-3" style="font-size:1.4rem;color:#1a7f4b;">
        <i class="fa fa-check-circle" aria-hidden="true"></i>
        <?php echo get_string('codesready_title', 'local_registrationcodes'); ?>
      </h2>

      <?php if (empty($codes)): ?>
        <div class="alert alert-warning">
          <?php echo get_string('codesready_notfound', 'local_registrationcodes'); ?>
          <br><small style="opacity:.7;">order: <?php echo s($order_id); ?></small>
        </div>
      <?php else: ?>
        <p class="text-muted mb-3">
          <?php echo get_string('codesready_intro', 'local_registrationcodes'); ?>
        </p>

        <?php
        $code_strings = array_column((array) $codes, 'code');
        $plain_list   = implode("\n", $code_strings);
        ?>

        <textarea id="al-codes-list" class="form-control mb-3"
                  rows="<?php echo min(count($codes), 15); ?>"
                  readonly
                  style="font-family:monospace;font-size:1rem;direction:ltr;text-align:left;"
        ><?php echo s($plain_list); ?></textarea>

        <button class="btn btn-outline-secondary btn-sm mb-4" onclick="alCopyAll()">
          <i class="fa fa-copy" aria-hidden="true"></i>
          <?php echo get_string('codesready_copy', 'local_registrationcodes'); ?>
        </button>

        <table class="table table-sm table-bordered" style="font-size:.95rem;">
          <thead class="thead-light">
            <tr>
              <th style="width:2.5rem;">#</th>
              <th>الكود</th>
              <th style="width:8rem;">الحالة</th>
            </tr>
          </thead>
          <tbody>
            <?php $i = 1; foreach ($codes as $c): ?>
            <tr>
              <td><?php echo $i++; ?></td>
              <td style="font-family:monospace;direction:ltr;text-align:left;">
                <?php echo s($c->code); ?>
              </td>
              <td>
                <?php
                $badge = $c->status === 'unused' ? 'badge-success' : 'badge-secondary';
                echo '<span class="badge ' . $badge . '">' . s($c->status) . '</span>';
                ?>
              </td>
            </tr>
            <?php endforeach; ?>
          </tbody>
        </table>

        <p class="text-muted" style="font-size:.85rem;">
          إجمالي الأكواد: <strong><?php echo count($codes); ?></strong>
          &nbsp;|&nbsp; رقم الطلب: <code><?php echo s($order_id); ?></code>
        </p>
      <?php endif; ?>

      <a href="<?php echo (new moodle_url('/local/registrationcodes/buy.php'))->out(false); ?>"
         class="btn btn-primary">
        <i class="fa fa-plus" aria-hidden="true"></i>
        شراء المزيد من الأكواد
      </a>
    </div>
  </div>
</div>

<script>
function alCopyAll() {
    var ta = document.getElementById('al-codes-list');
    if (!ta) return;
    ta.select();
    ta.setSelectionRange(0, 99999);
    try {
        document.execCommand('copy');
        alert('تم نسخ الأكواد!');
    } catch (e) {
        navigator.clipboard && navigator.clipboard.writeText(ta.value);
    }
}
</script>
<?php

echo $OUTPUT->footer();
